version: '3'
services:
  python-app-main1:
    container_name: python-app-main1
    image: hvxuser/python-app-main:latest
    restart: always

  python-app-main2:
    container_name: python-app-main2
    image: hvxuser/python-app-main:latest
    restart: always

  python-app-main3:
    container_name: python-app-main3
    image: hvxuser/python-app-main:latest
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 8000:8000
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./log/nginx:/var/log/nginx
    depends_on:
      - python-app-main1
      - python-app-main2
      - python-app-main3
